### ISSUE TITLE
幕布公益版 / 教育特惠

### ISSUE THREAD

**Issue by rosuH** [ivmm/Student-resources#10]
> 「公益计划」是幕布面向学生、公益组织和教育机构推出的专属优惠措施，对于符合申请条件的用户，我们会提供八折购买高级版的优惠；面对大型公益机构，我们也愿意提供专门的服务支持。 
幕布会承担起相应的社会责任，希望我们的努力能让这个世界更美好一点。

![snipaste_20170904_220356.png](https://i.loli.net/2017/09/04/59ad5d457458f.png)

[幕布公益版申请表](http://cn.mikecrm.com/BrUWPMy)

**Comment by ivmm** [comment]
ok，幕布不错的哟~
