### ISSUE TITLE
Mathematica 学生 3 折

### ISSUE THREAD

**Issue by sukanka** [ivmm/Student-resources#13]
Mathematica 凭edu 邮箱或者学生证，能够购买学生版，虽然页面显示155，但是点进去之后就变成了50美元，需要VISA 或者 Mastercard. 不知道Paypal 行不行。链接在[这里](http://www.wolfram.com/mathematica/pricing/students-individuals.php)

**Comment by ivmm** [comment]
已经添加了，的确是50刀，不过貌似要先添加学生证，后续看反馈吧，如果买不了就撤下来好了
