### ISSUE TITLE
Microsoft Imagine 似乎已经不可用了

### ISSUE THREAD

**Issue by Rocket1184** [ivmm/Student-resources#14]
使用 Chrome 打开之后显示证书错误。忽略错误打开之后，只有一行：

```
您要找的资源已被删除、已更名或暂时不可用。
```

在 GitHub 的学生包里面倒是可以看见 Microsoft Imagine 的标识。

是不是可以考虑在列表中删去 Microsoft Imagine 这一项。

**Comment by shenlw** [comment]
用这个网址打开就可以了：[Microsoft Imagine](https://imagine.microsoft.com/)

**Comment by luoxufeiyan** [comment]
之前的链接是DreamSpark的，现在已经改名为Microsoft Imagine了，用@shenlw 给的链接即可。

[软件和开发工具下载 | Imagine](https://imagine.microsoft.com/zh-cn/catalog)

**Comment by ivmm** [comment]
我更新一下域名
