### ISSUE TITLE
学生没有信用卡怎么使用

### ISSUE THREAD

**Issue by pprp** [ivmm/Student-resources#20]
好多学生应用包括goolge cloud, bitnami等资源都需要有visa等国外承认的信用卡才能使用,大学生没有收入所以没有信用卡,国内的借记卡也无法使用,请问你有什么推荐么?
非常感谢您的帮助

**Comment by HFO4** [comment]
有些银行有学生信用卡的

**Comment by pprp** [comment]
@HFO4 好多都不过审,你用的是哪个银行的?

**Comment by NeverBehave** [comment]
Google cloud是可以使用国内的visa借记卡，验证时会要求你上传网银截图

**Comment by sukanka** [comment]
@pprp  招商银行的可以办,我办过一张银联,一张Mastercard,还有3k额度,现在都2018年了,很多银行都开始发校园卡了.

**Comment by kmahyyg** [comment]
http://www.boc.cn/bcservice/bc3/bc31/201704/t20170426_9329452.html

**Comment by pprp** [comment]
谢谢你们的帮助，我会实践一下的
