### ISSUE TITLE
JetBrains 学生包

### ISSUE THREAD

**Issue by jiuxiaxixi** [ivmm/Student-resources#21]
# 时间只有1年么
**可以重复获得资格么**

**Comment by chamankoon** [comment]
可以的, 只要你到时仍是在校生, 在当次证书到期可以更新授权证书. 
> How can I renew my free educational license for another year?
> If you're still studying/teaching at a full-time educational program, you can renew your free license for another year. To do so, use the dedicated link in your JetBrains account, or use a link from the automatic email reminder we send out one week before your subscription expires.

From: [https://www.jetbrains.com/student/](url)

**Comment by ivmm** [comment]
@chamankoon  回答的是正解，谢谢chamankoon
