### ISSUE TITLE
设计师图片管理工具Eagle 教育优惠

### ISSUE THREAD

**Issue by LauItachi** [ivmm/Student-resources#27]
根据[Eagle官网FAQ](https://cn.eagle.cool/faq)，教育、公益机构提供 7 折优惠，原价199，优惠价139，需提供身份和证件信息。
可试用一个月。
优秀的本地图片管理工具，搭配学生版OneDrive进行同步管理，美滋滋。

**Comment by LauItachi** [comment]
已添加Pull Request，请查看。
（顺便Eagle已下手学生版，挺舒服的）

**Comment by ivmm** [comment]
谢谢支持
