### ISSUE TITLE
笔记工具Notion.so对教育用户免费了

### ISSUE THREAD

**Issue by luoxufeiyan** [ivmm/Student-resources#37]
官网链接：https://www.notion.so/students
Notion可以记笔记，做团队协同和整理清单，是一款好用的笔记类工具。
目前验证学校邮箱可以免费升级为Personal套餐，可保存无限数量笔记和不限大小的附件。

**Comment by LauItachi** [comment]
优秀哇 马上就去试了一波
支持Web、PC、IOS、Mac，粉了

**Comment by wangkun19930608** [comment]
福利真不错！就是网络有点慢，有点难受，有用过[Coda](https://www.chaoqi.net/xinchao/2019/0716/225498.html)的伙伴没？同样优秀的一个产品，只是同样网络慢，有伙伴有更好的解决办法木？幕布会员除外。

**Comment by ivmm** [comment]
已经体添加，谢谢
