### ISSUE TITLE
100rmb畅读1年O'Reilly的电子书库

### ISSUE THREAD

**Issue by michaelfyc** [ivmm/Student-resources#38]
注册成为CCF会员后缴纳年会费（学生会员一年50r），通过CCF可以再交50r便可成为ACM会员。通过ACM会员账号可以自由阅读O'Reilly的电子书。注册不需要教育邮箱，但是学籍必须真实可查。
CCF每月25日（如遇假日或周末则顺延）会将缴纳ACM会费的申请者名单提交给ACM，最晚在次月10日前将发送确认邮件，最快两天后就能收到邮件。O'Reilly系列的书一般都比较贵，100r畅读一年原版电子书几乎比Kindle Unlimted还香了。
（在线阅读访问较慢，可能需要木弟子）

**Comment by zhouweitong3** [comment]
刚交完会费，坑爹的选了非学生，不过资源看样子确实挺多的

**Comment by breakTBB** [comment]
在学校时白嫖了一年acm会员，现在都要过期了，还不知道这个权利...
