### ISSUE TITLE
阿里云云翼计划最新的活动

### ISSUE THREAD

**Issue by Penghaiku** [ivmm/Student-resources#43]
- [**阿里云** + **云翼计划**](https://developer.aliyun.com/adc/student/?tdsourcetag=s_pctim_aiomsg)
    1. 配置：2核、4G内存、1Mbps、40g硬盘
    2. 价格：免费赠送6个月

**Comment by Alex-1-2** [comment]
没看到啊

**Comment by Penghaiku** [comment]
https://developer.aliyun.com/adc/student/?tdsourcetag=s_pctim_aiomsg

**Comment by Penghaiku** [comment]
这个活动已经坚挺一个月了

**Comment by alienyan** [comment]
之前说到2月8号没想到现在还有
