### ISSUE TITLE
建议加入教育优惠所需要的认证条件

### ISSUE THREAD

**Issue by Zyilin98** [ivmm/Student-resources#68]
建议加入 教育优惠所需要的认证条件 
例如 1.学信网认证 2.教育邮箱认证 3.提交材料认证
这样能更直观的表示出哪些更容易获取，因为有些学校不愿意提供教育邮箱或者提供证明

另外，网易UU加速器似乎是可以通过学信网认证，得到一个减免的
戴尔的学生优惠一般是购机的时候从官方商城去找客服大部分时候优惠都是500元左右（实话实说这个优惠很多时候加完了还没PDD百亿补贴来的便宜）

**Comment by ivmm** [comment]
网易UU加速器 已经添加，
所需要的认证条件工作量太大，主要是我都毕业好几年了，也没办法去验证了。
一般来说国内很少走教育邮箱，都走学信网。 国外的话，把学生证翻译一下基本上也能过。

感谢提醒
