### ISSUE TITLE
大疆教育优惠

### ISSUE THREAD

**Issue by TinkoLiu** [ivmm/Student-resources#7]
大疆教育折扣
http://coupon.dji.com/cn/edu
适用于大疆官方商城的大部分商品。新品发布约3-6个月后可享受教育折扣。折扣程度较低。

大疆科研开发教育折扣
http://coupon.dji.com/cn/research
DJI大疆开发平台产品教育折扣，限支持DJI SDK的产品。目前在获得当地政府认可的高等院校与学院就读的学生或任职的教职工。拥有合法获得的高校邮箱或教育邮箱。该高校邮箱或教育邮箱已在developer.dji.com开发者官网注册成为DJI开发者并接受到验证邮件。

大疆高校RoboMaster参赛队教育折扣
https://www.robomasters.com/
价格低到爆，开发套件优惠，前提是以队伍形式代表学校参赛。

**Comment by ivmm** [comment]
多谢提醒，已经添加
